CREATE SCHEMA PLADIPUS;

USE PLADIPUS;

CREATE  TABLE IF NOT EXISTS USERS (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `USER_NAME` TEXT NOT NULL ,
  `CONTACT` TEXT NOT NULL ,
  `PASSWORD` TEXT NOT NULL ,
  PRIMARY KEY (`USER_ID`) );

CREATE  TABLE IF NOT EXISTS USER_ROLES (
  `USER_ID` INT(11) NOT NULL ,
  `ROLE_ID` INT(11) NOT NULL 
 );

CREATE  TABLE IF NOT EXISTS ROLES (
  `ROLE_ID` INT(11) NOT NULL ,
  `ROLE` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`ROLE_ID`));

CREATE  TABLE IF NOT EXISTS RUN (
  `RUN_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `TITLE` TEXT NULL DEFAULT NULL ,
  `USER_NAME` TEXT NULL DEFAULT NULL ,
  `TEMPLATE` TEXT NULL DEFAULT NULL ,
  PRIMARY KEY (`RUN_ID`) );

CREATE  TABLE IF NOT EXISTS PROCESS (
  `PROCESS_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `RUN_ID` INT(11) NOT NULL ,
  `FAILCOUNT` INT(11) NULL DEFAULT '0' ,
  `STEPCOUNT` INT(11) NULL DEFAULT '0' ,
  `STATE` TEXT NULL DEFAULT NULL ,
  `COMPLETE` TINYINT(1) NULL DEFAULT '0' ,
  `ON_QUEUE` TINYINT(1) NULL DEFAULT '0' ,
  PRIMARY KEY (`PROCESS_ID`) );

CREATE  TABLE IF NOT EXISTS PROCESS_PARAMETERS (
  `PROCESS_ID` INT(11) NOT NULL ,
  `NAME` TEXT NOT NULL ,
  `VALUE` TEXT NOT NULL);

INSERT INTO ROLES(ROLE_ID,ROLE) VALUES(1,'ADMIN');
INSERT INTO ROLES(ROLE_ID,ROLE) VALUES(2,'USER');

INSERT INTO USERS(USER_NAME,CONTACT,PASSWORD) VALUES('pladmin','pladipus@ugent.be','qh1mFAwsB9evmvD+gXeoY58dGU9ze72oIb4648t66BGt4jzV9TM/72z8GezdPKN3');
  
INSERT INTO USER_ROLES(USER_ID,ROLE_ID) VALUES(1,1);