package com.compomics.pladipus.view;

import com.compomics.pladipus.core.control.distribution.service.RunService;
import com.compomics.pladipus.core.control.distribution.service.queue.CompomicsProducer;
import com.compomics.pladipus.core.control.distribution.service.queue.jmx.operation.impl.DeleteOperation;
import com.compomics.pladipus.core.control.distribution.service.queue.jmx.operation.impl.QueryOperation;
import com.compomics.pladipus.core.model.processing.standard.maintenance.MaintenanceTask;
import com.compomics.pladipus.core.model.processing.templates.PladipusProcessingTemplate;
import com.compomics.pladipus.core.model.processing.templates.ProcessingParameterTemplate;
import com.compomics.pladipus.core.model.queue.CompomicsQueue;
import com.compomics.pladipus.view.dialogs.user.UserCreationDialog;
import com.compomics.pladipus.view.dialogs.user.UserPriviledgeDialog;
import com.compomics.util.gui.renderers.AlignedListCellRenderer;
import com.sun.glass.events.KeyEvent;
import com.sun.mail.iap.ConnectionException;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.jms.JMSException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

/**
 *
 * @author Kenneth Verheggen
 */
public class AdminConsole extends javax.swing.JFrame {

    /**
     * The logged in user
     */
    private final String user;

    /**
     * Creates a new AdminConsole.
     */
    public AdminConsole(String user) {
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.user = user;
        // try to set the look and feel
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // ignore error, use default look and feel
        }
        initComponents();
        cbMaintenanceTasks.setRenderer(new AlignedListCellRenderer(SwingConstants.CENTER));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/pladipus_icon.gif")));
        initMaintenanceSteps();
        pladipusInformationPanel1.activate();
    }

    private void initMaintenanceSteps() {
        cbMaintenanceTasks.removeAllItems();
        for (MaintenanceTask task : MaintenanceTask.values()) {
            cbMaintenanceTasks.addItem(task);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnPurgeDatabase = new javax.swing.JButton();
        cbMaintenanceTasks = new javax.swing.JComboBox();
        btnBroadcast = new javax.swing.JButton();
        btnPurge = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pladipusInformationPanel1 = new com.compomics.pladipus.view.panels.impl.PladipusInformationPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        btnGetUserRuns = new javax.swing.JButton();
        userPanel1 = new com.compomics.pladipus.view.panels.impl.UserPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miCreateUser = new javax.swing.JMenuItem();
        miPrivilegeUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Settings");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Server Operations"));

        btnPurgeDatabase.setText("Purge Database");
        btnPurgeDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurgeDatabaseActionPerformed(evt);
            }
        });

        cbMaintenanceTasks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shutdown", "Reboot", "Update Processbeans" }));

        btnBroadcast.setText("Broadcast");
        btnBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBroadcastActionPerformed(evt);
            }
        });

        btnPurge.setText("Purge Queue");
        btnPurge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPurge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPurgeDatabase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMaintenanceTasks, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBroadcast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPurge, btnPurgeDatabase, cbMaintenanceTasks});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMaintenanceTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBroadcast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPurgeDatabase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPurge)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBroadcast, btnPurge, btnPurgeDatabase, cbMaintenanceTasks});

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pladipus"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pladipusInformationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pladipusInformationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maintenance", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Username");

        tfUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfUserNameKeyReleased(evt);
            }
        });

        btnGetUserRuns.setText("Get Runs");
        btnGetUserRuns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetUserRunsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGetUserRuns)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetUserRuns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Database", jPanel3);

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('U');
        jMenu2.setText("Users");

        miCreateUser.setMnemonic('N');
        miCreateUser.setText("New User...");
        miCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCreateUserActionPerformed(evt);
            }
        });
        jMenu2.add(miCreateUser);

        miPrivilegeUser.setMnemonic('C');
        miPrivilegeUser.setText("Change Privileges");
        miPrivilegeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrivilegeUserActionPerformed(evt);
            }
        });
        jMenu2.add(miPrivilegeUser);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPrivilegeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrivilegeUserActionPerformed
        try {
            new UserPriviledgeDialog(this, true).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminConsole.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miPrivilegeUserActionPerformed

    private void miCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreateUserActionPerformed
        new UserCreationDialog(this, true).setVisible(true);
    }//GEN-LAST:event_miCreateUserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnGetUserRunsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetUserRunsActionPerformed
        userPanel1.deactivate();
        userPanel1.setUser(tfUserName.getText());
        userPanel1.activate();
    }//GEN-LAST:event_btnGetUserRunsActionPerformed

    private void btnPurgeDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurgeDatabaseActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to empty all data in the database except for users?", "Are you sure?", JOptionPane.YES_NO_OPTION);
        if (dialogResult == 0) {
            try {
                RunService service = RunService.getInstance();
                service.truncate();
            } catch (Exception ex) {
                Logger.getLogger(AdminConsole.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPurgeDatabaseActionPerformed

    private void btnPurgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurgeActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete all messages on the queue?", "Are you sure?", JOptionPane.YES_NO_OPTION);
        if (dialogResult == 0) {
            try {
                DeleteOperation operation = new DeleteOperation();
                operation.purgeQueue(CompomicsQueue.JOB);
            } catch (Exception ex) {
                Logger.getLogger(AdminConsole.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPurgeActionPerformed

    private void btnBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBroadcastActionPerformed
        try {
            MaintenanceTask task = (MaintenanceTask) cbMaintenanceTasks.getSelectedItem();

            String operationName = "Maintenance_" + task + System.currentTimeMillis();
            PladipusProcessingTemplate template = new PladipusProcessingTemplate(operationName, user, 1);

            //URGENT need to stop on CANCEL
            if (task.equals(MaintenanceTask.UPDATE_PROCESSBEANS)) {
                String beanClass = JOptionPane.showInputDialog(this, "Please specify the new, fully defined class name", "Broadcast information required", JOptionPane.OK_CANCEL_OPTION);
                if ((beanClass != null) && (beanClass.length() > 0)) {
                    ProcessingParameterTemplate parameter = new ProcessingParameterTemplate("className", beanClass);
                    template.addRunParameter(parameter);
                } else {
                    return;
                }
            }

            template.addProcessingStep(task.getClassName());

            QueryOperation qOperation = new QueryOperation();
            long cumulativeQueueSize = 1;
            try {
                cumulativeQueueSize = qOperation.getCumulativeQueueSize(CompomicsQueue.UPDATE);
            } catch (Exception ex) {
//queue might not be made yet

            }
            template.toJobXML((int) cumulativeQueueSize);

            CompomicsProducer producer = new CompomicsProducer(CompomicsQueue.UPDATE, user, -1);
            Thread producerThread = new Thread(producer, "ProducerThread");
            producerThread.start();

        } catch (IOException | JMSException ex) {
            Logger.getLogger(AdminConsole.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ConnectionException ex) {
            Logger.getLogger(AdminConsole.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBroadcastActionPerformed

    private void tfUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserNameKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnGetUserRunsActionPerformed(null);
        }
    }//GEN-LAST:event_tfUserNameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminConsole adminConsole = new AdminConsole("kenneth");
                adminConsole.setLocationRelativeTo(null);
                adminConsole.setTitle("Administration Console");
                adminConsole.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBroadcast;
    private javax.swing.JButton btnGetUserRuns;
    private javax.swing.JButton btnPurge;
    private javax.swing.JButton btnPurgeDatabase;
    private javax.swing.JComboBox cbMaintenanceTasks;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem miCreateUser;
    private javax.swing.JMenuItem miPrivilegeUser;
    private com.compomics.pladipus.view.panels.impl.PladipusInformationPanel pladipusInformationPanel1;
    private javax.swing.JTextField tfUserName;
    private com.compomics.pladipus.view.panels.impl.UserPanel userPanel1;
    // End of variables declaration//GEN-END:variables
}
