package com.compomics.pladipus.view;

import com.compomics.pladipus.core.model.properties.NetworkProperties;
import org.apache.ibatis.jdbc.ScriptRunner;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenneth Verheggen
 */
public class MySQLPanel extends javax.swing.JPanel {

    //todo add logging

    /**
     * Creates new form MySQLPanel
     */
    public MySQLPanel() {
        initComponents();
        ImageIcon image = new ImageIcon(
                getClass().getResource(
                        "/images/logo_mysql.png"));
        lbLogo.setText("");
        lbLogo.setIcon(image);
    }

    public void setWorkerMode(boolean isWorkerMode) {
        btnInstallDatabase.setEnabled(!isWorkerMode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblHost = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        tfHost = new javax.swing.JTextField();
        tfPort = new javax.swing.JTextField();
        tfUser = new javax.swing.JTextField();
        btnApply = new javax.swing.JButton();
        pfPass = new javax.swing.JPasswordField();
        btnInstallDatabase = new javax.swing.JButton();
        btnTestConnection = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        lblHost.setBackground(new java.awt.Color(255, 255, 255));
        lblHost.setText("Host");

        lblPort.setBackground(new java.awt.Color(255, 255, 255));
        lblPort.setText("Port");

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setText("User");

        lblPass.setBackground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Password");

        tfHost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHost.setText("localhost");
        tfHost.setToolTipText("This is the IP adress of the machine hosting the MySQL database");

        tfPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPort.setText("3306");
        tfPort.setToolTipText("This is the open port of the host where the MySQL service is listening on ");

        tfUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUser.setText("root");
        tfUser.setToolTipText("The login to the database with correct privileges");

        btnApply.setText("Save Settings");
        btnApply.addActionListener(this::btnApplyActionPerformed);

        pfPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfPass.setToolTipText("The password for the login");

        btnInstallDatabase.setText("Import DB");
        btnInstallDatabase.addActionListener(this::btnInstallDatabaseActionPerformed);

        btnTestConnection.setText("Test Connection");
        btnTestConnection.addActionListener(this::btnTestConnectionActionPerformed);

        lbLogo.setBackground(new java.awt.Color(255, 255, 255));
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("jLabel1");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lblHost, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfHost))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPort, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUser)
                            .addComponent(tfPort)))
                    .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTestConnection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(btnInstallDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApply, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addComponent(pfPass))))
                .addContainerGap())
        );

        pnlMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, lblHost, lblPass, lblPort, lblUser);

        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHost)
                    .addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInstallDatabase)
                    .addComponent(btnApply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTestConnection)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        testConnection(true);
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnInstallDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallDatabaseActionPerformed
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://" + tfHost.getText() + ":" + tfPort.getText(), tfUser.getText(), new String(pfPass.getPassword()))) {
            if (pladipusExists(connection)) {
                int answer = JOptionPane.showConfirmDialog(this, "The database already exists. Would you like to perform a clean install?");
                if (answer == JOptionPane.YES_OPTION) {
                    answer = JOptionPane.showConfirmDialog(this, "Are you sure? This action can not be undone?");
                    if (answer == JOptionPane.YES_OPTION) {
                        dropPladipus(connection);
                    } else {
                        return;
                    }
                } else {
                    return;
                }
            }
            setupMySql(connection);
            if (pladipusExists(connection)) {
                JOptionPane.showMessageDialog(null, "Succesfully initiated database.", "Database import complete", JOptionPane.INFORMATION_MESSAGE);
            } else {
                throw new IOException("Could not create database schema. Are the privileges set correctly for the specified account?");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Could not connect to the database: " + System.lineSeparator() + ex.getMessage(),
                    "Connection Failed",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Could not import the database: " + System.lineSeparator() + ex.getMessage(),
                    "Import Failed",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInstallDatabaseActionPerformed

    private void btnTestConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestConnectionActionPerformed
        testConnection(false);
    }//GEN-LAST:event_btnTestConnectionActionPerformed

    private void testConnection(boolean save) {
        //1. check if db exists
        //todo add field for db name and save to properties
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://" + tfHost.getText() + ":" + tfPort.getText(), tfUser.getText(), new String(pfPass.getPassword()))) {
            try {
                if (pladipusExists(connection)) {
                    if (save) {
                        NetworkProperties properties = NetworkProperties.getInstance();

                        properties.setProperty("db.host", tfHost.getText());
                        properties.setProperty("db.port", tfPort.getText());
                        properties.setProperty("db.login",tfUser.getText());
                        //todo either encrypt password or ask it each time
                        //properties.setProperty("db.pass", new String(pfPass.getPassword()));
                        properties.save();
                        JOptionPane.showMessageDialog(this, "Succesfully saved database settings.", "Database settings saved", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Succesfully contacted the Pladipus database.", "Database connected", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } catch (SQLException exception) {
                if (!connection.isClosed()) {
                    //2. prompt login to initialize the database
                    int dialogResult = JOptionPane.showConfirmDialog(this, "Would you like to automatically import the Pladipus database?");
                    if (dialogResult == JOptionPane.YES_OPTION) {
                        JOptionPane.showMessageDialog(null, "Succesfully initiated database.", "Database import complete", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Could not connect to the database: " + System.lineSeparator() + exception.getMessage(),
                            "Connection Failed",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            if (e.getMessage().contains("Access denied for login")) {
                JOptionPane.showMessageDialog(this,
                        "The password was incorrect or the login has no privileges...",
                        "Connection Failed",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            //custom title, error icon
            JOptionPane.showMessageDialog(this,
                    "Could not import SQL init script." + System.lineSeparator() + ex.getMessage(),
                    "Database Creation Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    //todo: moved backend functionality into panel, to move all non visual functionality away from this panel

    /**
     * drops the pladipus schema
     *
     * @param connection connection to the database to drop the scheme from
     * @return true if success
     * @throws SQLException
     */
    public boolean dropPladipus(Connection connection) throws SQLException {
        try (PreparedStatement stat = connection.prepareStatement("drop schema pladipus;")) {
            return stat.execute();
        }
    }

    /**
     * checks if the pladipus schema exists
     *
     * @param connection the connection to the database to check on
     * @return true if success
     * @throws SQLException
     */
    public boolean pladipusExists(Connection connection) throws SQLException {

        try (PreparedStatement stat = connection.prepareStatement("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'pladipus'")) {
            try (ResultSet set = stat.executeQuery()) {
                return (!set.isAfterLast() && !set.isBeforeFirst());
            }
        }
    }

    /**
     * Installs the pladipus database on the given connection. Note,you need
     * create rights for this on the server !
     *
     * @param connection the connection to mysql
     * @throws IOException
     */
    public boolean setupMySql(Connection connection) throws IOException {

        //don't quite like this runner thing
        //2. import from SQL script?
        ScriptRunner runner = new ScriptRunner(connection);
        runner.setAutoCommit(true);
        runner.setStopOnError(true);
        try (InputStream in = getClass().getClassLoader().getResourceAsStream("doc/PLADIPUS_INIT_SCRIPT.sql")) {
            if (in != null) {
                runner.runScript(new InputStreamReader(in));
                runner.closeConnection();
                return true;
            } else {
                throw new FileNotFoundException("could not find sql script to import");
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnInstallDatabase;
    private javax.swing.JButton btnTestConnection;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField tfHost;
    private javax.swing.JTextField tfPort;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
