package com.compomics.pladipus.view;

import com.compomics.pladipus.controller.setup.InstallExample;
import com.compomics.pladipus.controller.setup.InstallPladipus;
import com.compomics.util.gui.waiting.waitinghandlers.ProgressDialogX;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Davy Maddelein
 */
public class PladipusWorkerPanel extends javax.swing.JPanel {

    /**
     * Creates new form PladipusWorkerPanel
     */
    public PladipusWorkerPanel() {
        initComponents();
    }

        private void installPladipusWorker() {
        ProgressDialogX dialog = new ProgressDialogX(true);

        new Thread(() -> {
            try {
                if (new InstallPladipus().installWorker()) {
                    JOptionPane.showMessageDialog(this, "Succesfully installed Pladipus Worker.", "Pladipus Worker", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SecurityException | IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Could not install Pladipus Worker: " + System.lineSeparator() + ex.getMessage(),
                        "Worker Error",
                        JOptionPane.ERROR_MESSAGE);
            } finally {
                dialog.setRunFinished();
                dialog.setVisible(false);
                dialog.dispose();
            }
        }).start();
        dialog.setLocationRelativeTo(null);
        dialog.setPrimaryProgressCounterIndeterminate(true);
        dialog.setTitle("Installing Pladipus Worker");
        dialog.setVisible(true);
    }
        
        private void installBasicSetup(){
            //todo make users able to choose what steps to add
            new InstallExample().install();
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(177, 238));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pladipus_icon.gif"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 140));

        jButton1.setText("install worker");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        installPladipusWorker();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
