/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.pladipus.view;

import com.compomics.pladipus.controller.setup.InstallExample;
import com.compomics.pladipus.controller.setup.InstallPladipus;
import com.compomics.pladipus.view.dialogs.user.UserCreationDialog;
import com.compomics.util.gui.waiting.waitinghandlers.ProgressDialogX;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenneth Verheggen
 */
public class PladipusPanel extends javax.swing.JPanel {

    /**
     * Creates new form MySQLPanel
     */
    public PladipusPanel() {
        initComponents();
        ImageIcon image = new ImageIcon(
                getClass().getResource(
                        "/images/pladipus_icon.gif"));
        lbLogo.setText("");
        lbLogo.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        pnlLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        btnInstallGUI = new javax.swing.JButton();
        btnInstallWorker = new javax.swing.JButton();
        btnInstallExample = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register new user");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        pnlLogo.setBackground(new java.awt.Color(255, 255, 255));

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("jLabel1");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnInstallGUI.setBackground(new java.awt.Color(255, 255, 255));
        btnInstallGUI.setText("Install Management-mode");
        btnInstallGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallGUIActionPerformed(evt);
            }
        });

        btnInstallWorker.setBackground(new java.awt.Color(255, 255, 255));
        btnInstallWorker.setText("Install Execution-mode");
        btnInstallWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallWorkerActionPerformed(evt);
            }
        });

        btnInstallExample.setBackground(new java.awt.Color(255, 255, 255));
        btnInstallExample.setText("Install Example Tools");
        btnInstallExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallExampleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegister)
                    .addComponent(btnInstallGUI)
                    .addComponent(btnInstallWorker)
                    .addComponent(btnInstallExample))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInstallExample, btnInstallGUI, btnInstallWorker, btnRegister});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInstallGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInstallWorker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInstallExample)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        UserCreationDialog userCreationDialog = new UserCreationDialog(null, true);
        userCreationDialog.setLocationRelativeTo(this);
        userCreationDialog.setTitle("New Pladipus user");
        userCreationDialog.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnInstallGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallGUIActionPerformed
        ProgressDialogX dialog = new ProgressDialogX(true);

        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    new InstallPladipus().installConsole();
                    JOptionPane.showMessageDialog(PladipusPanel.this, "Succesfully installed Pladipus console");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(PladipusPanel.this,
                            "Could not install Pladipus console : " + System.lineSeparator() + ex.getMessage(),
                            "Console error",
                            JOptionPane.ERROR_MESSAGE);
                } finally {
                    dialog.setRunFinished();
                    dialog.setVisible(false);
                    dialog.dispose();
                }
            }
        }).start();
        dialog.setLocationRelativeTo(null);
        dialog.setPrimaryProgressCounterIndeterminate(true);
        dialog.setTitle("Installing Pladipus console");
        dialog.setVisible(true);
    }//GEN-LAST:event_btnInstallGUIActionPerformed

    private void btnInstallWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallWorkerActionPerformed
         ProgressDialogX dialog = new ProgressDialogX(true);

        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    new InstallPladipus().installWorker();
                    JOptionPane.showMessageDialog(PladipusPanel.this, "Succesfully installed Pladipus executor");
                } catch (SecurityException|IOException ex) {
                    JOptionPane.showMessageDialog(PladipusPanel.this,
                            "Could not install Pladipus executor : " + System.lineSeparator() + ex.getMessage(),
                            "Executor error",
                            JOptionPane.ERROR_MESSAGE);
                } finally {
                    dialog.setRunFinished();
                    dialog.setVisible(false);
                    dialog.dispose();
                }
            }
        }).start();
        dialog.setLocationRelativeTo(null);
        dialog.setPrimaryProgressCounterIndeterminate(true);
        dialog.setTitle("Installing Pladipus Worker");
        dialog.setVisible(true);
    }//GEN-LAST:event_btnInstallWorkerActionPerformed

    private void btnInstallExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallExampleActionPerformed
        new InstallExample().install();
    }//GEN-LAST:event_btnInstallExampleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstallExample;
    private javax.swing.JButton btnInstallGUI;
    private javax.swing.JButton btnInstallWorker;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
