package com.compomics.pladipus.view;

import com.compomics.pladipus.controller.setup.InstallPladipus;
import com.compomics.pladipus.model.PladipusCard;
import com.compomics.pladipus.view.dialogs.user.UserCreationDialog;
import com.compomics.util.gui.waiting.waitinghandlers.ProgressDialogX;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Davy Maddelein
 */
public class PladipusManagerPanel extends javax.swing.JPanel implements PladipusCard {

    /**
     * Creates new form PladipusManagerPanel
     */
    public PladipusManagerPanel() {
        initComponents();
    }
    
        @Override
    public String getCardDescription(){
        return "<h2>Step 3 of 3 - Pladipus</h2>"
                + "<br>"
                + "This step will install the pladipus manager"
                + "it also includes the creation of a Pladipus user, which is needed to submit, manage or execute tasks"
                + "<br><br>"
                + "Click <a href='https://github.com/compomics/pladipus/wiki/1.-Installation'>here</a> for more help."
                ;
    }

    @Override
    public String getFriendlyName(){
        return "Installing Pladipus Manager";
    }
    
    private void createPladipusUser(){
        UserCreationDialog userCreationDialog = new UserCreationDialog(null, true);
        userCreationDialog.setLocationRelativeTo(null);
        userCreationDialog.setTitle("New Pladipus User");
        userCreationDialog.setVisible(true);
    }
    
        private void installPladipusManagement() {
        ProgressDialogX dialog = new ProgressDialogX(true);

        new Thread(() -> {
            try {
                new InstallPladipus().installConsole();
                JOptionPane.showMessageDialog(this, "Succesfully installed Pladipus Manager.", "Pladipus Manager", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Could not install Pladipus Manager: " + System.lineSeparator() + ex.getMessage(),
                        "Manager Error",
                        JOptionPane.ERROR_MESSAGE);
            } finally {
                dialog.setRunFinished();
                dialog.setVisible(false);
                dialog.dispose();
            }
        }).start();
        dialog.setLocationRelativeTo(null);
        dialog.setPrimaryProgressCounterIndeterminate(true);
        dialog.setTitle("Installing Pladipus Manager");
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(177, 238));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pladipus_icon.gif"))); // NOI18N

        jButton1.setText("install manager");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        installPladipusManagement();
        createPladipusUser();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
