package com.compomics.pladipus.view;

import com.compomics.pladipus.controller.setup.InstallExample;
import com.compomics.pladipus.controller.setup.InstallPladipus;
import com.compomics.pladipus.view.dialogs.user.UserCreationDialog;
import com.compomics.util.gui.waiting.waitinghandlers.ProgressDialogX;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenneth Verheggen
 */
public class PladipusPanel extends javax.swing.JPanel {

    /**
     * Creates a new MySQLPanel.
     */
    public PladipusPanel() {
        initComponents();
        ImageIcon image = new ImageIcon(
                getClass().getResource(
                        "/images/pladipus_icon.gif"));
        lbLogo.setText("");
        lbLogo.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        pnlLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        btnInstallGUI = new javax.swing.JButton();
        btnInstallWorker = new javax.swing.JButton();
        btnInstallExample = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnRegister.setText("Register New User");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        pnlLogo.setBackground(new java.awt.Color(255, 255, 255));

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("jLabel1");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );

        btnInstallGUI.setText("Install Manager");
        btnInstallGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallGUIActionPerformed(evt);
            }
        });

        btnInstallWorker.setText("Install Worker");
        btnInstallWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallWorkerActionPerformed(evt);
            }
        });

        btnInstallExample.setText("Install Example Tools");
        btnInstallExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallExampleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInstallGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInstallWorker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInstallExample, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInstallGUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInstallWorker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInstallExample)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        UserCreationDialog userCreationDialog = new UserCreationDialog(null, true);
        userCreationDialog.setLocationRelativeTo(this);
        userCreationDialog.setTitle("New Pladipus user");
        userCreationDialog.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnInstallGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallGUIActionPerformed
        ProgressDialogX dialog = new ProgressDialogX(true);

        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    new InstallPladipus().installConsole();
                    JOptionPane.showMessageDialog(PladipusPanel.this, "Succesfully installed Pladipus console");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(PladipusPanel.this,
                            "Could not install Pladipus console : " + System.lineSeparator() + ex.getMessage(),
                            "Console error",
                            JOptionPane.ERROR_MESSAGE);
                } finally {
                    dialog.setRunFinished();
                    dialog.setVisible(false);
                    dialog.dispose();
                }
            }
        }).start();
        dialog.setLocationRelativeTo(null);
        dialog.setPrimaryProgressCounterIndeterminate(true);
        dialog.setTitle("Installing Pladipus console");
        dialog.setVisible(true);
    }//GEN-LAST:event_btnInstallGUIActionPerformed

    private void btnInstallWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallWorkerActionPerformed
        ProgressDialogX dialog = new ProgressDialogX(true);

        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    new InstallPladipus().installWorker();
                    JOptionPane.showMessageDialog(PladipusPanel.this, "Succesfully installed Pladipus executor");
                } catch (SecurityException | IOException ex) {
                    JOptionPane.showMessageDialog(PladipusPanel.this,
                            "Could not install Pladipus executor : " + System.lineSeparator() + ex.getMessage(),
                            "Executor error",
                            JOptionPane.ERROR_MESSAGE);
                } finally {
                    dialog.setRunFinished();
                    dialog.setVisible(false);
                    dialog.dispose();
                }
            }
        }).start();
        dialog.setLocationRelativeTo(null);
        dialog.setPrimaryProgressCounterIndeterminate(true);
        dialog.setTitle("Installing Pladipus Worker");
        dialog.setVisible(true);
    }//GEN-LAST:event_btnInstallWorkerActionPerformed

    private void btnInstallExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallExampleActionPerformed
        new InstallExample().install();
    }//GEN-LAST:event_btnInstallExampleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstallExample;
    private javax.swing.JButton btnInstallGUI;
    private javax.swing.JButton btnInstallWorker;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
