package com.compomics.pladipus.view;

import javax.swing.ImageIcon;

/**
 *
 * @author Kenneth Verheggen
 */
public class SplashPanel extends javax.swing.JPanel {

    /**
     * Creates a new PladipusPanel.
     */
    public SplashPanel() {
        initComponents();
         btnGroupModes.add(btnInstallWorker);
        btnGroupModes.add(btnInstallManagement);
        ImageIcon image = new ImageIcon(
                getClass().getResource(
                        "/images/pladipus_icon.gif"));
        lbLogo.setText("");
        lbLogo.setIcon(image);
    }

    public boolean isInstallManagementMode() {
        return btnInstallManagement.isSelected();
    }

    public boolean isInstallWorkerMode() {
        return btnInstallWorker.isSelected();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupModes = new javax.swing.ButtonGroup();
        pnlLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        btnInstallManagement = new javax.swing.JRadioButton();
        btnInstallWorker = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlLogo.setBackground(new java.awt.Color(255, 255, 255));

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("jLabel1");

        btnInstallManagement.setBackground(new java.awt.Color(255, 255, 255));
        btnInstallManagement.setSelected(true);
        btnInstallManagement.setText("Install Manager");
        btnInstallManagement.setIconTextGap(15);

        btnInstallWorker.setBackground(new java.awt.Color(255, 255, 255));
        btnInstallWorker.setText("Install Worker");
        btnInstallWorker.setIconTextGap(15);

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInstallManagement)
                    .addComponent(btnInstallWorker))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnInstallManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInstallWorker)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupModes;
    private javax.swing.JRadioButton btnInstallManagement;
    private javax.swing.JRadioButton btnInstallWorker;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
