/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.pladipus.view;

import com.compomics.pladipus.model.PladipusCard;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * panel to contain all the pladipus install steps in a card layout
 * @author Davy Maddelein
 */
public class StepsCardPanel extends javax.swing.JPanel {

    private final List<String> cards = new ArrayList<>();

    CardLayout layout;

    int currentCard = 0;
    
    /**
     * Creates new form StepsCardPanel
     */
    public StepsCardPanel() {
        initComponents();
        layout = (CardLayout) getLayout();
    }

    public StepsCardPanel(Component[] components){
        this();
        setLayout(layout);
        for(Component aComponent : components){
            add(aComponent, aComponent.getClass().getName());
            cards.add(aComponent.getClass().getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    public void showPreviousCard() {

        if(currentCard != 0){
            currentCard -= 1;
        }
        layout.show(this,cards.get(currentCard));
    }

    public void showNextCard() {

        if(currentCard != cards.size()){
            currentCard += 1;
        }
        layout.show(this,cards.get(currentCard));
    }

    public boolean hasNext() {
        return currentCard != cards.size();
    }

    public boolean hasPrevious() {
        return currentCard != 0;
    }

    public String getCardDescription() {
        //todo clean this up
        return ((PladipusCard)getComponent(currentCard)).getCardDescription();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
