/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.pladipus.view.dialogs.run;

import com.compomics.pladipus.core.control.distribution.service.database.dao.impl.RunDAO;
import com.compomics.pladipus.core.model.processing.templates.PladipusProcessingTemplate;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenneth
 */
public class ProcessCreationDialog extends javax.swing.JDialog {

    /**
     * The template to create a job from
     */
    private final PladipusProcessingTemplate template;

    /**
     * Creates new form ProcessCreationDialog
     */
    public ProcessCreationDialog(java.awt.Frame parent, boolean modal, PladipusProcessingTemplate template) {
        super(parent, modal);
        this.template = template;
        initComponents();
        initTable();
        spnlParameters.getViewport().setOpaque(false);
    }

    private void initTable() {
                //load the job parameters in the jTable
        DefaultTableModel model = (DefaultTableModel) tblParameters.getModel();;
        for (String aParameterName : template.getJobParameters().keySet()) {
            System.out.println(aParameterName);
            model.addRow(new String[]{aParameterName, ""});
        }
        tblParameters.setModel(model);
        tblParameters.repaint();
        tblParameters.addKeyListener(new KeyAdapter() {
            private int row;
            @Override
            public void keyReleased(KeyEvent e) {
                int maxRows = tblParameters.getModel().getRowCount();
                if (e.getKeyCode() == KeyEvent.VK_TAB) {
                    row = tblParameters.getSelectedRow();
                    while (tblParameters.isCellEditable(row, 1) == false) {
                        if (row == maxRows) {
                            row = 0;
                        }
                        row++;
                    }
                    tblParameters.editCellAt(row, 1);
                    tblParameters.requestFocusInWindow();

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        spnlParameters = new javax.swing.JScrollPane();
        tblParameters = new javax.swing.JTable();
        mnBar = new javax.swing.JMenuBar();
        miFile = new javax.swing.JMenu();
        miImport = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMain.setBackground(java.awt.Color.white);

        btnCreate.setBackground(java.awt.Color.white);
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        spnlParameters.setBackground(new java.awt.Color(255, 255, 255));
        spnlParameters.setBorder(null);
        spnlParameters.setOpaque(false);

        tblParameters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parameter", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblParameters.setOpaque(false);
        tblParameters.setSelectionBackground(new java.awt.Color(255, 255, 255));
        spnlParameters.setViewportView(tblParameters);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addContainerGap())
            .addComponent(spnlParameters)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addComponent(spnlParameters, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreate)
                .addContainerGap())
        );

        miFile.setText("File");

        miImport.setText("Import job(s)...");
        miImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportActionPerformed(evt);
            }
        });
        miFile.add(miImport);

        miExit.setText("Exit");
        miFile.add(miExit);

        mnBar.add(miFile);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            HashMap<String, String> parameterMap = readParametersFromTable();
            RunDAO rDAO = RunDAO.getInstance();
            int runID = rDAO.getRunID(template.getName(), template.getUser());
            rDAO.addToRun(runID, parameterMap);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ProcessCreationDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void miImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportActionPerformed
        ProcessImportDialog dialog = new ProcessImportDialog(null, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_miImportActionPerformed

    private HashMap<String, String> readParametersFromTable() {
        HashMap<String, String> parameterMap = new HashMap<>();
        DefaultTableModel model = (DefaultTableModel) tblParameters.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            parameterMap.put(String.valueOf(model.getValueAt(i, 0)), String.valueOf(model.getValueAt(i, 1)));
        }
        return parameterMap;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenu miFile;
    private javax.swing.JMenuItem miImport;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane spnlParameters;
    private javax.swing.JTable tblParameters;
    // End of variables declaration//GEN-END:variables
}
